scripts/create-validators.sh
scripts/start-beacon-node.sh
scripts/start-geth.sh
scripts/start-validator-client.sh

Fixes https://github.com/sigp/lighthouse/issues/839.
Running the commands in the shell script without `exec` leads to SIGTERM signals not reaching the application. (Source https://hynek.me/articles/docker-signals/ point 2)

Run all shell script commands with exec

---

docker-compose.yml

Also moves `env_file` below `ports` to be consistent with other container specs above

Add missing start geth command

---

default.env
scripts/start-beacon-node.sh

Make the graffiti flag configurable through an environment variable so the user doesn't need to make code changes to the startup script.
This is useful e.g. to earn the POAP badge for medalla testnet launch: https://medalla.beaconcha.in/poap

Configure graffiti through $GRAFFITI

---

scripts/start-beacon-node.sh

Needed as per https://github.com/sigp/lighthouse/releases/tag/v0.2.4

added --max-skip-slots to beacon node start script

---

scripts/start-geth.sh

At startup geth prints
```
WARN [08-06|19:23:26.749] The flag --rpc is deprecated and will be removed in the future, please use --http 
WARN [08-06|19:23:26.749] The flag --rpcaddr is deprecated and will be removed in the future, please use --http.addr 
WARN [08-06|19:23:26.749] The flag --rpcvhosts is deprecated and will be removed in the future, please use --http.vhosts
```
This PR updates the deprecated flags.

Update deprecated HTTP-RPC flags

---

.gitignore
docker-compose.yml

Fixes #17 
Some pitfalls which may need to be addressed with a good documentation or a `entrypoint.sh`
- The already existing data needs to be `chown` to the new `lighthouse` user (uid: 999)
- The `validator_definitions.yml` needs to be edited to use the new paths

Adopted all path to user lighthouse instead of root

---

.gitignore
docker-compose.yml

It would be nice to have `geth` data files also next to `docker-compose` configuration the same way we have there `lighthouse` data.
It is nice when in need of wiping or inspecting the data, so we don't need to dig deep somewhere in `/var/lib/docker/volumes/lighthousedocker_geth/_data/`.

have geth data files on the same place as lighthouse data

---

default.env
docker-compose.yml
scripts/start-beacon-node.sh
scripts/start-validator-client.sh

Currently, even though we support multiple networks in docker, we don't have good support for multiple datadirs for these networks.
The current directory structure is a mess and it's pretty hard to specify the right flags in a docker setup.
This will be easier once https://github.com/sigp/lighthouse/pull/1532 gets merged. 
However, since spadina launch is tomorrow, this PR aims to be sort of a temporary fix to support multiple networks using existing directory flags.
The directory structure will be similar to the above linked PR (top level `~/.lighthouse` and a directory for every named testnet).
For the user who was running medalla and wants to run spadina now, the steps would be
1. Create a new `medalla` folder in `lighthouse-data` and move all folders inside the new `medalla` …

Support multiple datadirs for multiple networks

---

.gitignore
default.env
docker-compose.yml
scripts/start-validator-client.sh

This PR makes it possible to move `validator_keys` folder created with `eth2.0-deposit-cli` to `lighthouse-docker` project root and have `lighthouse-docker` import the keystores.
The current way of creating a wallet and deriving validators exposes the seed (and withdrawal key) to the (most likely internet connected) docker host. Importing `eth2.0-deposit-cli` keystores is important since it lets me keep the seed and withdrawal key offline.

Support importing launchpad validators

---

default.env
docker-compose.yml
scripts/start-beacon-node.sh

A few minor changes to enable beacon node's metrics endpoint using ENABLE_METRICS env var.

Use env to enable beacon node metrics endpoint

---

default.env

Added `pyrmont` in default.env TESTNET comment.

Added pyrmont in default.env TESTNET comment

---

default.env
scripts/start-beacon-node.sh

Added support for fallback nodes as stated in release [v1.0.1](https://github.com/sigp/lighthouse/releases/tag/v1.0.1). Multiple nodes can now be specified in `VOTING_ETH1_NODES` environment variable.

Changed beacon node flag --eth1-endpoint to --eth1-endpoints

---

default.env
scripts/start-beacon-node.sh

Added flag to resolve issues related to `GetDepositLogsFailed` https://github.com/sigp/lighthouse/pull/1931
This is relevant to PR for fallback nodes https://github.com/sigp/lighthouse-docker/pull/45.

Added --eth1-blocks-per-log-query flag to allow to reduce blocks searched for deposit logs

---

scripts/start-beacon-node.sh

The WebSockets flags have been removed in the latest `unstable`, so we should delete them before the next release

delete ws flags and max skip slots

---

default.env
docker-compose.yml

The current behavior is to pull the docker image tagged as `latest`, which is equivalent to latest master branch. Before mainnet launch I think this behavior should probably be changed so that users pull a proper release instead.
Additionally, any sort of auto-update mechanism is probably a bad idea when it comes to running node, as sometimes a release might require actions from the user, sometimes it might mean joining a contentious fork etc.
This PR contains one way to configure and pin software versions.

Configurable lighthouse and geth docker tags

---

scripts/start-geth.sh

`--nousb` is the default in v1.10.x and the flag is deprecated

Remove the deprecated geth --nousb flag

---

scripts/start-beacon-node.sh

This fixes an error we get on beacon node startup:
```
/root/scripts/start-beacon-node.sh: 27: [: !=: argument expected`
```

Add missing space

---

default.env
scripts/start-beacon-node.sh

Added `PRIVATE` configuration variable to enable `--private` flag as stated in release [v1.0.3](https://github.com/sigp/lighthouse/releases/tag/v1.0.3).

Enable --private flag via config

---

default.env
scripts/start-validator-client.sh

Added `VOTING_ETH2_NODES` environment variable to specify redundant beacon nodes which is possible since `--beacon-nodes` in [v1.0.5](https://github.com/sigp/lighthouse/releases/tag/v1.0.5).

Allow specifying redundant beacon nodes

---

default.env
scripts/start-validator-client.sh

Adds option to enable doppelganger protection introduced in [v1.0.5](https://github.com/sigp/lighthouse/releases/tag/v1.5.0).

Add --enable-doppelganger-protection argument

---

default.env
scripts/start-beacon-node.sh

- Added automatic checkout sync and `CHECKPOINT_SYNC_URL` variable in `default.env`.

Added--checkpoint-sync-url param for beacon node
